<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ncc\\abstracts\\exceptioncodes' => '/Abstracts/ExceptionCodes.php',
                'ncc\\abstracts\\regexpatterns' => '/Abstracts/RegexPatterns.php',
                'ncc\\exceptions\\invalidprojectconfigurationexception' => '/Exceptions/InvalidProjectConfigurationException.php',
                'ncc\\ncc' => '/ncc.php',
                'ncc\\objects\\projectconfiguration' => '/Objects/ProjectConfiguration.php',
                'ncc\\objects\\projectconfiguration\\assembly' => '/Objects/ProjectConfiguration/Assembly.php',
                'ncc\\objects\\projectconfiguration\\build' => '/Objects/ProjectConfiguration/Build.php',
                'ncc\\objects\\projectconfiguration\\buildconfiguration' => '/Objects/ProjectConfiguration/BuildConfiguration.php',
                'ncc\\objects\\projectconfiguration\\compiler' => '/Objects/ProjectConfiguration/Compiler.php',
                'ncc\\objects\\projectconfiguration\\dependency' => '/Objects/ProjectConfiguration/Dependency.php',
                'ncc\\objects\\projectconfiguration\\project' => '/Objects/ProjectConfiguration/Project.php',
                'ncc\\utilities\\functions' => '/Utilities/Functions.php',
                'ncc\\utilities\\validate' => '/Utilities/Validate.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
