<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ncc\\abstracts\\exceptioncodes' => '/Abstracts/ExceptionCodes.php',
                'ncc\\abstracts\\regexpatterns' => '/Abstracts/RegexPatterns.php',
                'ncc\\exceptions\\filenotfoundexception' => '/Exceptions/FileNotFoundException.php',
                'ncc\\exceptions\\invalidprojectconfigurationexception' => '/Exceptions/InvalidProjectConfigurationException.php',
                'ncc\\ncc' => '/ncc.php',
                'ncc\\objects\\projectconfiguration' => '/Objects/ProjectConfiguration.php',
                'ncc\\objects\\projectconfiguration\\assembly' => '/Objects/ProjectConfiguration/Assembly.php',
                'ncc\\objects\\projectconfiguration\\build' => '/Objects/ProjectConfiguration/Build.php',
                'ncc\\objects\\projectconfiguration\\buildconfiguration' => '/Objects/ProjectConfiguration/BuildConfiguration.php',
                'ncc\\objects\\projectconfiguration\\compiler' => '/Objects/ProjectConfiguration/Compiler.php',
                'ncc\\objects\\projectconfiguration\\dependency' => '/Objects/ProjectConfiguration/Dependency.php',
                'ncc\\objects\\projectconfiguration\\project' => '/Objects/ProjectConfiguration/Project.php',
                'ncc\\utilities\\functions' => '/Utilities/Functions.php',
                'ncc\\utilities\\validate' => '/Utilities/Validate.php',
                'ncc\PhpSchool\\climenu\\action\\exitaction' => '/ThirdParty/php-school/cli-menu/Action/ExitAction.php',
                'ncc\PhpSchool\\climenu\\action\\gobackaction' => '/ThirdParty/php-school/cli-menu/Action/GoBackAction.php',
                'ncc\PhpSchool\\climenu\\builder\\climenubuilder' => '/ThirdParty/php-school/cli-menu/Builder/CliMenuBuilder.php',
                'ncc\PhpSchool\\climenu\\builder\\splititembuilder' => '/ThirdParty/php-school/cli-menu/Builder/SplitItemBuilder.php',
                'ncc\PhpSchool\\climenu\\climenu' => '/ThirdParty/php-school/cli-menu/CliMenu.php',
                'ncc\PhpSchool\\climenu\\dialogue\\cancellableconfirm' => '/ThirdParty/php-school/cli-menu/Dialogue/CancellableConfirm.php',
                'ncc\PhpSchool\\climenu\\dialogue\\confirm' => '/ThirdParty/php-school/cli-menu/Dialogue/Confirm.php',
                'ncc\PhpSchool\\climenu\\dialogue\\dialogue' => '/ThirdParty/php-school/cli-menu/Dialogue/Dialogue.php',
                'ncc\PhpSchool\\climenu\\dialogue\\flash' => '/ThirdParty/php-school/cli-menu/Dialogue/Flash.php',
                'ncc\PhpSchool\\climenu\\exception\\cannotshrinkmenuexception' => '/ThirdParty/php-school/cli-menu/Exception/CannotShrinkMenuException.php',
                'ncc\PhpSchool\\climenu\\exception\\invalidshortcutexception' => '/ThirdParty/php-school/cli-menu/Exception/InvalidShortcutException.php',
                'ncc\PhpSchool\\climenu\\exception\\invalidterminalexception' => '/ThirdParty/php-school/cli-menu/Exception/InvalidTerminalException.php',
                'ncc\PhpSchool\\climenu\\exception\\menunotopenexception' => '/ThirdParty/php-school/cli-menu/Exception/MenuNotOpenException.php',
                'ncc\PhpSchool\\climenu\\frame' => '/ThirdParty/php-school/cli-menu/Frame.php',
                'ncc\PhpSchool\\climenu\\input\\input' => '/ThirdParty/php-school/cli-menu/Input/Input.php',
                'ncc\PhpSchool\\climenu\\input\\inputio' => '/ThirdParty/php-school/cli-menu/Input/InputIO.php',
                'ncc\PhpSchool\\climenu\\input\\inputresult' => '/ThirdParty/php-school/cli-menu/Input/InputResult.php',
                'ncc\PhpSchool\\climenu\\input\\number' => '/ThirdParty/php-school/cli-menu/Input/Number.php',
                'ncc\PhpSchool\\climenu\\input\\password' => '/ThirdParty/php-school/cli-menu/Input/Password.php',
                'ncc\PhpSchool\\climenu\\input\\text' => '/ThirdParty/php-school/cli-menu/Input/Text.php',
                'ncc\PhpSchool\\climenu\\menuitem\\asciiartitem' => '/ThirdParty/php-school/cli-menu/MenuItem/AsciiArtItem.php',
                'ncc\PhpSchool\\climenu\\menuitem\\checkboxitem' => '/ThirdParty/php-school/cli-menu/MenuItem/CheckboxItem.php',
                'ncc\PhpSchool\\climenu\\menuitem\\linebreakitem' => '/ThirdParty/php-school/cli-menu/MenuItem/LineBreakItem.php',
                'ncc\PhpSchool\\climenu\\menuitem\\menuiteminterface' => '/ThirdParty/php-school/cli-menu/MenuItem/MenuItemInterface.php',
                'ncc\PhpSchool\\climenu\\menuitem\\menumenuitem' => '/ThirdParty/php-school/cli-menu/MenuItem/MenuMenuItem.php',
                'ncc\PhpSchool\\climenu\\menuitem\\propagatesstyles' => '/ThirdParty/php-school/cli-menu/MenuItem/PropagatesStyles.php',
                'ncc\PhpSchool\\climenu\\menuitem\\radioitem' => '/ThirdParty/php-school/cli-menu/MenuItem/RadioItem.php',
                'ncc\PhpSchool\\climenu\\menuitem\\selectableitem' => '/ThirdParty/php-school/cli-menu/MenuItem/SelectableItem.php',
                'ncc\PhpSchool\\climenu\\menuitem\\selectableitemrenderer' => '/ThirdParty/php-school/cli-menu/MenuItem/SelectableItemRenderer.php',
                'ncc\PhpSchool\\climenu\\menuitem\\splititem' => '/ThirdParty/php-school/cli-menu/MenuItem/SplitItem.php',
                'ncc\PhpSchool\\climenu\\menuitem\\staticitem' => '/ThirdParty/php-school/cli-menu/MenuItem/StaticItem.php',
                'ncc\PhpSchool\\climenu\\menustyle' => '/ThirdParty/php-school/cli-menu/MenuStyle.php',
                'ncc\PhpSchool\\climenu\\style\\checkboxstyle' => '/ThirdParty/php-school/cli-menu/Style/CheckboxStyle.php',
                'ncc\PhpSchool\\climenu\\style\\defaultstyle' => '/ThirdParty/php-school/cli-menu/Style/DefaultStyle.php',
                'ncc\PhpSchool\\climenu\\style\\exception\\invalidstyle' => '/ThirdParty/php-school/cli-menu/Style/Exception/InvalidStyle.php',
                'ncc\PhpSchool\\climenu\\style\\itemstyle' => '/ThirdParty/php-school/cli-menu/Style/ItemStyle.php',
                'ncc\PhpSchool\\climenu\\style\\locator' => '/ThirdParty/php-school/cli-menu/Style/Locator.php',
                'ncc\PhpSchool\\climenu\\style\\radiostyle' => '/ThirdParty/php-school/cli-menu/Style/RadioStyle.php',
                'ncc\PhpSchool\\climenu\\style\\selectablestyle' => '/ThirdParty/php-school/cli-menu/Style/SelectableStyle.php',
                'ncc\PhpSchool\\climenu\\terminal\\terminalfactory' => '/ThirdParty/php-school/cli-menu/Terminal/TerminalFactory.php',
                'ncc\PhpSchool\\climenu\\util\\collection' => '/ThirdParty/php-school/cli-menu/Util/Collection.php',
                'ncc\PhpSchool\\climenu\\util\\colourutil' => '/ThirdParty/php-school/cli-menu/Util/ColourUtil.php',
                'ncc\PhpSchool\\climenu\\util\\stringutil' => '/ThirdParty/php-school/cli-menu/Util/StringUtil.php',
                'ncc\Symfony\\component\\nccprocess\\exception\\exceptioninterface' => '/ThirdParty/Symfony/Process/Exception/ExceptionInterface.php',
                'ncc\Symfony\\component\\nccprocess\\exception\\invalidargumentexception' => '/ThirdParty/Symfony/Process/Exception/InvalidArgumentException.php',
                'ncc\Symfony\\component\\nccprocess\\exception\\logicexception' => '/ThirdParty/Symfony/Process/Exception/LogicException.php',
                'ncc\Symfony\\component\\nccprocess\\exception\\processfailedexception' => '/ThirdParty/Symfony/Process/Exception/ProcessFailedException.php',
                'ncc\Symfony\\component\\nccprocess\\exception\\processsignaledexception' => '/ThirdParty/Symfony/Process/Exception/ProcessSignaledException.php',
                'ncc\Symfony\\component\\nccprocess\\exception\\processtimedoutexception' => '/ThirdParty/Symfony/Process/Exception/ProcessTimedOutException.php',
                'ncc\Symfony\\component\\nccprocess\\exception\\runtimeexception' => '/ThirdParty/Symfony/Process/Exception/RuntimeException.php',
                'ncc\Symfony\\component\\nccprocess\\executablefinder' => '/ThirdParty/Symfony/Process/ExecutableFinder.php',
                'ncc\Symfony\\component\\nccprocess\\inputstream' => '/ThirdParty/Symfony/Process/InputStream.php',
                'ncc\Symfony\\component\\nccprocess\\phpexecutablefinder' => '/ThirdParty/Symfony/Process/PhpExecutableFinder.php',
                'ncc\Symfony\\component\\nccprocess\\phpprocess' => '/ThirdParty/Symfony/Process/PhpProcess.php',
                'ncc\Symfony\\component\\nccprocess\\pipes\\abstractpipes' => '/ThirdParty/Symfony/Process/Pipes/AbstractPipes.php',
                'ncc\Symfony\\component\\nccprocess\\pipes\\pipesinterface' => '/ThirdParty/Symfony/Process/Pipes/PipesInterface.php',
                'ncc\Symfony\\component\\nccprocess\\pipes\\unixpipes' => '/ThirdParty/Symfony/Process/Pipes/UnixPipes.php',
                'ncc\Symfony\\component\\nccprocess\\pipes\\windowspipes' => '/ThirdParty/Symfony/Process/Pipes/WindowsPipes.php',
                'ncc\Symfony\\component\\nccprocess\\process' => '/ThirdParty/Symfony/Process/Process.php',
                'ncc\Symfony\\component\\nccprocess\\processutils' => '/ThirdParty/Symfony/Process/ProcessUtils.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
