#!/bin/bash

# ------------------------------------------------------------------
# Nosial Code Compiler (NCC) Installation Script
#
#          Nosial Code Compiler is a program written in PHP designed
#          to be a multi-purpose compiler, package manager and toolkit.
#
# Dependency:
#     PHP 8.0+
# ------------------------------------------------------------------
