# NCC Default configuration file, upon installation the installer
# will generate a new configuration file for your system or update
# the existing configuration file and only overwriting values that
# are no longer applicable to the current version of NCC, incorrect
# configuration values can cause unexpected behavior or bugs.
ncc:
  cli:
    # Omits colors from displaying in the CLI
    no_colors: false

    # Display basic ascii characters in the CLI
    basic_ascii: false

    # The default logging level to use in the CLI
    # Values can be (silent, verbose, debug, info, warn, error or fatal)
    logging: "info"